# theme: jekyll-theme-minimal
title: Kristall's homepage
description: My Personal notes and codes

collections:
  projects:
    output: true
  research:
    output: true

markdown: kramdown
theme: minima
